[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y curl ffmpeg python3",
    "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp",
    "chmod a+rx /usr/local/bin/yt-dlp"
]

[phases.install]
cmds = ["cargo build --release"]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/social-downloader-bot"